// Redundant token sequences found by scripts/find-rewrites.mjs and confirmed by scripts/verify-rules.mjs
// (plus literal/argument drops). Generated data: regenerate and re-verify rather than editing by hand.
// Format: left side (2-3 token kinds) -> replacement; see rewrite.js.
export const FOUND = {
'#I drop':[],
'#I swap drop':['drop','#I'],
'#S drop':[],
'#S swap drop':['drop','#S'],
'#L drop':[],
'#L swap drop':['drop','#L'],
'#M drop':[],
'#M swap drop':['drop','#M'],
'#W drop':[],
'#W swap drop':['drop','#W'],
'n drop':[],
'n swap drop':['drop','n'],
'm drop':[],
'm swap drop':['drop','m'],
'k drop':[],
'k swap drop':['drop','k'],
'0 -':[],
'0 +':[],
'0 drop':[],
'0 pad':[],
'0 pair sum':[],
'0 rotate':[],
'0 skip':[],
'1 *':[],
'1 drop':[],
'1 pow':[],
'1 rep':[],
'10 drop':[],
'2 drop':[],
'alpha drop':[],
'ALPHA drop':[],
'chars flat':[],
'digs drop':[],
'dup abs min2':[],
'dup dec max2':[],
'dup drop':[],
'dup inc min2':[],
'dup inter':[],
'dup max2':[],
'dup min2':[],
'group flat':[],
'halves flat':[],
'neg neg':[],
'ord chr':[],
'over drop':[],
'perms head':[],
'powerset last':[],
'prefixes last':[],
'rev rev':[],
'rot rot rot':[],
'suffixes head':[],
'swap swap':[],
'wrap flat':[],
'wrap head':[],
'wrap last':[],
'0 1 <':['1'],
'0 1 =':['0'],
'0 1 >':['0'],
'0 1 max2':['1'],
'0 1 min2':['0'],
'0 10 *':['0'],
'0 10 /':['0'],
'0 10 %':['0'],
'0 10 +':['10'],
'0 10 <':['1'],
'0 10 =':['0'],
'0 10 >':['0'],
'0 10 max2':['10'],
'0 10 min2':['0'],
'0 2 /':['0'],
'0 2 %':['0'],
'0 2 +':['2'],
'0 2 <':['1'],
'0 2 =':['0'],
'0 2 >':['0'],
'0 2 max2':['2'],
'0 2 min2':['0'],
'0 abs':['0'],
'0 ceil':['0'],
'0 chunks':['wrap'],
'0 dec -':['inc'],
'0 dec *':['neg'],
'0 dec +':['dec'],
'0 dec abs':['1'],
'0 dec inc':['0'],
'0 dec neg':['1'],
'0 dec not':['0'],
'0 dec sq':['1'],
'0 dsum':['0'],
'0 dup -':['0'],
'0 dup /':['0'],
'0 dup %':['0'],
'0 dup +':['0'],
'0 dup <':['0'],
'0 dup =':['1'],
'0 even':['1'],
'0 fact':['1'],
'0 fib':['0'],
'0 floor':['0'],
'0 frac':['0'],
'0 gcd':['abs'],
'0 inc':['1'],
'0 isint':['1'],
'0 isqrt':['0'],
'0 issq':['1'],
'0 neg':['0'],
'0 not':['1'],
'0 nthp':['0'],
'0 over +':['dup'],
'0 prime':['0'],
'0 rot +':['swap'],
'0 round':['0'],
'0 sign':['0'],
'0 sq':['0'],
'0 sqrt':['0'],
'0 swap -':['neg'],
'1 -':['dec'],
'1 /':['floor'],
'1 %':['frac'],
'1 +':['inc'],
'1 0 <':['0'],
'1 0 =':['0'],
'1 0 >':['1'],
'1 0 max2':['1'],
'1 0 min2':['0'],
'1 10 *':['10'],
'1 10 /':['0'],
'1 10 %':['1'],
'1 10 <':['1'],
'1 10 =':['0'],
'1 10 >':['0'],
'1 10 max2':['10'],
'1 10 min2':['1'],
'1 2 /':['0'],
'1 2 %':['1'],
'1 2 <':['1'],
'1 2 =':['0'],
'1 2 >':['0'],
'1 2 max2':['2'],
'1 2 min2':['1'],
'1 abs':['1'],
'1 ceil':['1'],
'1 dec':['0'],
'1 dsum':['1'],
'1 dup -':['0'],
'1 dup /':['1'],
'1 dup %':['0'],
'1 dup +':['2'],
'1 dup <':['0'],
'1 dup =':['1'],
'1 dvd':['isint'],
'1 even':['0'],
'1 fact':['1'],
'1 fib':['1'],
'1 floor':['1'],
'1 frac':['0'],
'1 idx':['head'],
'1 inc':['2'],
'1 isint':['1'],
'1 isqrt':['1'],
'1 issq':['1'],
'1 min2 not':['not'],
'1 not':['0'],
'1 nthp':['2'],
'1 over *':['dup'],
'1 pair sum':['inc'],
'1 prime':['0'],
'1 rot *':['swap'],
'1 round':['1'],
'1 sign':['1'],
'1 skip':['tail'],
'1 sq':['1'],
'1 sqrt':['1'],
'1 ubase':['sum'],
'10 * not':['not'],
'10 + len':['len'],
'10 0 <':['0'],
'10 0 =':['0'],
'10 0 >':['1'],
'10 0 max2':['10'],
'10 0 min2':['0'],
'10 1 <':['0'],
'10 1 =':['0'],
'10 1 >':['1'],
'10 1 max2':['10'],
'10 1 min2':['1'],
'10 2 %':['0'],
'10 2 <':['0'],
'10 2 =':['0'],
'10 2 >':['1'],
'10 2 max2':['10'],
'10 2 min2':['2'],
'10 abs':['10'],
'10 base':['digits'],
'10 ceil':['10'],
'10 dec inc':['10'],
'10 dec not':['0'],
'10 dsum':['1'],
'10 dup -':['0'],
'10 dup /':['1'],
'10 dup %':['0'],
'10 dup <':['0'],
'10 dup =':['1'],
'10 even':['1'],
'10 floor':['10'],
'10 frac':['0'],
'10 inc dec':['10'],
'10 inc not':['0'],
'10 isint':['1'],
'10 issq':['0'],
'10 min2 not':['not'],
'10 not':['0'],
'10 prime':['0'],
'10 round':['10'],
'10 sign':['1'],
'10 sq not':['0'],
'10 ubase':['undig'],
'10 wrap sum':['10'],
'2 + len':['len'],
'2 0 <':['0'],
'2 0 =':['0'],
'2 0 >':['1'],
'2 0 max2':['2'],
'2 0 min2':['0'],
'2 1 <':['0'],
'2 1 =':['0'],
'2 1 >':['1'],
'2 1 max2':['2'],
'2 1 min2':['1'],
'2 10 /':['0'],
'2 10 %':['2'],
'2 10 <':['1'],
'2 10 =':['0'],
'2 10 >':['0'],
'2 10 max2':['10'],
'2 10 min2':['2'],
'2 abs':['2'],
'2 ceil':['2'],
'2 dec':['1'],
'2 dsum':['2'],
'2 dup -':['0'],
'2 dup /':['1'],
'2 dup %':['0'],
'2 dup <':['0'],
'2 dup =':['1'],
'2 dvd':['even'],
'2 even':['1'],
'2 fact':['2'],
'2 fib':['1'],
'2 floor':['2'],
'2 frac':['0'],
'2 inc dec':['2'],
'2 inc not':['0'],
'2 isint':['1'],
'2 isqrt':['1'],
'2 issq':['0'],
'2 min2 not':['not'],
'2 not':['0'],
'2 pow':['sq'],
'2 prime':['1'],
'2 round':['2'],
'2 sign':['1'],
'2 sq not':['0'],
'abs 0 max2':['abs'],
'abs abs':['abs'],
'abs all':['all'],
'abs any':['any'],
'abs drop':['drop'],
'abs even':['even'],
'abs isint':['isint'],
'abs keep':['keep'],
'abs len':['len'],
'abs lens':['lens'],
'abs not':['not'],
'abs pal':['pal'],
'abs sq':['sq'],
'abs where':['where'],
'all abs':['all'],
'all ceil':['all'],
'all drop':['drop'],
'all dsum':['all'],
'all fib':['all'],
'all floor':['all'],
'all isqrt':['all'],
'all len':['len'],
'all round':['all'],
'all sign':['all'],
'all sq':['all'],
'all sqrt':['all'],
'alpha low':['alpha'],
'ALPHA low':['alpha'],
'alpha num':['0'],
'ALPHA num':['0'],
'alpha pal':['0'],
'ALPHA pal':['0'],
'alpha sort':['alpha'],
'ALPHA sort':['ALPHA'],
'alpha split':['wrap'],
'ALPHA split':['wrap'],
'alpha uniq':['alpha'],
'ALPHA uniq':['ALPHA'],
'alpha up':['ALPHA'],
'ALPHA up':['ALPHA'],
'alt drop':['drop'],
'any abs':['any'],
'any ceil':['any'],
'any drop':['drop'],
'any dsum':['any'],
'any fib':['any'],
'any floor':['any'],
'any isqrt':['any'],
'any len':['len'],
'any round':['any'],
'any sign':['any'],
'any sq':['any'],
'any sqrt':['any'],
'bins drop':['drop'],
'bins uniq':['bins'],
'ceil ceil':['ceil'],
'ceil drop':['drop'],
'ceil fib':['fib'],
'ceil floor':['ceil'],
'ceil len':['len'],
'ceil lens':['lens'],
'ceil round':['ceil'],
'chars drop':['drop'],
'chars head':['head'],
'chars last':['last'],
'chars len':['len'],
'chars pal':['pal'],
'chr drop':['drop'],
'chr lens':['lens'],
'count abs':['count'],
'count ceil':['count'],
'count floor':['count'],
'count round':['count'],
'cumsum drop':['drop'],
'cumsum len':['len'],
'cumsum lens':['lens'],
'dec drop':['drop'],
'dec inc dec':['dec'],
'dec len':['len'],
'dec lens':['lens'],
'deltas drop':['drop'],
'digits abs':['digits'],
'digits ceil':['digits'],
'digits drop':['drop'],
'digits dsum':['digits'],
'digits floor':['digits'],
'digits round':['digits'],
'digits sum':['dsum'],
'digs len':['10'],
'digs low':['digs'],
'digs pal':['0'],
'digs sort':['digs'],
'digs uniq':['digs'],
'digs up':['digs'],
'divs abs':['divs'],
'divs ceil':['divs'],
'divs drop':['drop'],
'divs floor':['divs'],
'divs round':['divs'],
'divs sort':['divs'],
'divs uniq':['divs'],
'dsum abs':['dsum'],
'dsum ceil':['dsum'],
'dsum drop':['drop'],
'dsum floor':['dsum'],
'dsum len':['len'],
'dsum lens':['lens'],
'dsum round':['dsum'],
'dup *':['sq'],
'dup + len':['len'],
'dup + not':['not'],
'dup abs max2':['abs'],
'dup cat head':['head'],
'dup cat last':['last'],
'dup dec min2':['dec'],
'dup dup eql':['1'],
'dup eql *':['drop'],
'dup gcd':['abs'],
'dup inc max2':['inc'],
'dup neg max2':['abs'],
'dup rev eql':['pal'],
'dup swap':['dup'],
'dup wrap max2':['wrap'],
'dup wrap min2':['wrap'],
'eql 0 >':['eql'],
'eql 0 max2':['eql'],
'eql 1 =':['eql'],
'eql 1 min2':['eql'],
'eql 10 %':['eql'],
'eql 10 min2':['eql'],
'eql 2 %':['eql'],
'eql 2 min2':['eql'],
'eql abs':['eql'],
'eql ceil':['eql'],
'eql dec inc':['eql'],
'eql dec not':['eql'],
'eql dsum':['eql'],
'eql dup /':['eql'],
'eql fib':['eql'],
'eql floor':['eql'],
'eql inc dec':['eql'],
'eql isqrt':['eql'],
'eql not not':['eql'],
'eql round':['eql'],
'eql sign':['eql'],
'eql sq':['eql'],
'eql sqrt':['eql'],
'even abs':['even'],
'even ceil':['even'],
'even drop':['drop'],
'even dsum':['even'],
'even fib':['even'],
'even floor':['even'],
'even isqrt':['even'],
'even len':['len'],
'even lens':['lens'],
'even round':['even'],
'even sign':['even'],
'even sq':['even'],
'even sqrt':['even'],
'fact abs':['fact'],
'fact ceil':['fact'],
'fact drop':['drop'],
'fact floor':['fact'],
'fact len':['len'],
'fact lens':['lens'],
'fact round':['fact'],
'fib abs':['fib'],
'fib ceil':['fib'],
'fib drop':['drop'],
'fib floor':['fib'],
'fib len':['len'],
'fib lens':['lens'],
'fib round':['fib'],
'flat drop':['drop'],
'floor base':['base'],
'floor ceil':['floor'],
'floor chr':['chr'],
'floor digits':['digits'],
'floor drop':['drop'],
'floor dsum':['dsum'],
'floor fact':['fact'],
'floor floor':['floor'],
'floor idx':['idx'],
'floor iota0':['iota0'],
'floor isqrt':['isqrt'],
'floor len':['len'],
'floor lens':['lens'],
'floor pad':['pad'],
'floor primes':['primes'],
'floor range':['range'],
'floor rep':['rep'],
'floor round':['floor'],
'floor skip':['skip'],
'floor take':['take'],
'frac abs':['frac'],
'frac drop':['drop'],
'frac even':['isint'],
'frac len':['len'],
'frac lens':['lens'],
'grade abs':['grade'],
'grade ceil':['grade'],
'grade drop':['drop'],
'grade floor':['grade'],
'grade len':['len'],
'grade max':['len'],
'grade round':['grade'],
'grade uniq':['grade'],
'group drop':['drop'],
'group pal':['pal'],
'halves drop':['drop'],
'has abs':['has'],
'has ceil':['has'],
'has dsum':['has'],
'has fib':['has'],
'has floor':['has'],
'has isqrt':['has'],
'has round':['has'],
'has sign':['has'],
'has sq':['has'],
'has sqrt':['has'],
'head drop':['drop'],
'idxof abs':['idxof'],
'idxof ceil':['idxof'],
'idxof floor':['idxof'],
'idxof round':['idxof'],
'idxof sign':['has'],
'inc dec inc':['inc'],
'inc drop':['drop'],
'inc len':['len'],
'inc lens':['lens'],
'init drop':['drop'],
'iota0 abs':['iota0'],
'iota0 ceil':['iota0'],
'iota0 drop':['drop'],
'iota0 floor':['iota0'],
'iota0 grade':['range'],
'iota0 inc':['range'],
'iota0 round':['iota0'],
'iota0 sort':['iota0'],
'iota0 uniq':['iota0'],
'isint abs':['isint'],
'isint ceil':['isint'],
'isint drop':['drop'],
'isint dsum':['isint'],
'isint fib':['isint'],
'isint floor':['isint'],
'isint isqrt':['isint'],
'isint len':['len'],
'isint lens':['lens'],
'isint round':['isint'],
'isint sign':['isint'],
'isint sq':['isint'],
'isint sqrt':['isint'],
'isqrt abs':['isqrt'],
'isqrt ceil':['isqrt'],
'isqrt drop':['drop'],
'isqrt floor':['isqrt'],
'isqrt len':['len'],
'isqrt lens':['lens'],
'isqrt round':['isqrt'],
'issq abs':['issq'],
'issq ceil':['issq'],
'issq drop':['drop'],
'issq dsum':['issq'],
'issq fib':['issq'],
'issq floor':['issq'],
'issq isqrt':['issq'],
'issq len':['len'],
'issq lens':['lens'],
'issq round':['issq'],
'issq sign':['issq'],
'issq sq':['issq'],
'issq sqrt':['issq'],
'last drop':['drop'],
'len 0 max2':['len'],
'len abs':['len'],
'len ceil':['len'],
'len dec inc':['len'],
'len drop':['drop'],
'len floor':['len'],
'len inc dec':['len'],
'len round':['len'],
'len wrap sum':['len'],
'lens abs':['lens'],
'lens ceil':['lens'],
'lens drop':['drop'],
'lens floor':['lens'],
'lens len':['len'],
'lens round':['lens'],
'low drop':['drop'],
'low low':['low'],
'max drop':['drop'],
'max len':['len'],
'min drop':['drop'],
'min len':['len'],
'minmax drop':['drop'],
'minmax head':['min'],
'minmax last':['max'],
'minmax max':['max'],
'minmax min':['min'],
'minmax minmax':['minmax'],
'minmax sort':['minmax'],
'neg abs':['abs'],
'neg all':['all'],
'neg any':['any'],
'neg drop':['drop'],
'neg even':['even'],
'neg isint':['isint'],
'neg keep':['keep'],
'neg len':['len'],
'neg lens':['lens'],
'neg not':['not'],
'neg pal':['pal'],
'neg sq':['sq'],
'neg where':['where'],
'not 0 >':['not'],
'not 0 max2':['not'],
'not 1 =':['not'],
'not 1 min2':['not'],
'not 10 %':['not'],
'not 10 min2':['not'],
'not 2 %':['not'],
'not 2 min2':['not'],
'not abs':['not'],
'not ceil':['not'],
'not dec inc':['not'],
'not dec not':['not'],
'not drop':['drop'],
'not dsum':['not'],
'not dup /':['not'],
'not fib':['not'],
'not floor':['not'],
'not inc dec':['not'],
'not isqrt':['not'],
'not len':['len'],
'not lens':['lens'],
'not not not':['not'],
'not round':['not'],
'not sign':['not'],
'not sq':['not'],
'not sqrt':['not'],
'not sum not':['all'],
'nthp abs':['nthp'],
'nthp ceil':['nthp'],
'nthp drop':['drop'],
'nthp floor':['nthp'],
'nthp len':['len'],
'nthp lens':['lens'],
'nthp round':['nthp'],
'num drop':['drop'],
'num len':['len'],
'ord abs':['ord'],
'ord ceil':['ord'],
'ord drop':['drop'],
'ord floor':['ord'],
'ord len':['len'],
'ord lens':['lens'],
'ord pal':['pal'],
'ord round':['ord'],
'over dup eql':['1'],
'over max2 max2':['max2'],
'over min2 min2':['min2'],
'over swap rot':['over'],
'pair flat':['cat'],
'pair head':['drop'],
'pal abs':['pal'],
'pal ceil':['pal'],
'pal drop':['drop'],
'pal dsum':['pal'],
'pal fib':['pal'],
'pal floor':['pal'],
'pal isqrt':['pal'],
'pal round':['pal'],
'pal sign':['pal'],
'pal sq':['pal'],
'pal sqrt':['pal'],
'perms drop':['drop'],
'perms last':['rev'],
'perms pal':['pal'],
'pfac abs':['pfac'],
'pfac drop':['drop'],
'pfac sort':['pfac'],
'powerset drop':['drop'],
'prefixes drop':['drop'],
'prefixes len':['len'],
'prefixes sort':['prefixes'],
'prefixes sum':['cumsum'],
'prefixes uniq':['prefixes'],
'prime abs':['prime'],
'prime ceil':['prime'],
'prime drop':['drop'],
'prime dsum':['prime'],
'prime fib':['prime'],
'prime floor':['prime'],
'prime isqrt':['prime'],
'prime len':['len'],
'prime lens':['lens'],
'prime round':['prime'],
'prime sign':['prime'],
'prime sq':['prime'],
'prime sqrt':['prime'],
'primes abs':['primes'],
'primes ceil':['primes'],
'primes drop':['drop'],
'primes floor':['primes'],
'primes round':['primes'],
'primes sort':['primes'],
'primes uniq':['primes'],
'prod drop':['drop'],
'prod len':['len'],
'range abs':['range'],
'range ceil':['range'],
'range drop':['drop'],
'range floor':['range'],
'range grade':['range'],
'range keep':['take'],
'range round':['range'],
'range where':['range'],
'rev diff':['diff'],
'rev drop':['drop'],
'rev head':['last'],
'rev inter':['inter'],
'rev last':['head'],
'rev len':['len'],
'rev mdiff':['mdiff'],
'rev minmax':['minmax'],
'rev pal':['pal'],
'rev sum rev':['sum'],
'rng uniq':['rng'],
'rot swap rot':['swap'],
'round ceil':['round'],
'round drop':['drop'],
'round floor':['round'],
'round len':['len'],
'round lens':['lens'],
'round round':['round'],
'sign all':['all'],
'sign any':['any'],
'sign ceil':['sign'],
'sign drop':['drop'],
'sign even':['not'],
'sign floor':['sign'],
'sign keep':['keep'],
'sign len':['len'],
'sign lens':['lens'],
'sign not':['not'],
'sign round':['sign'],
'sign sign':['sign'],
'sign where':['where'],
'sort diff':['diff'],
'sort drop':['drop'],
'sort inter':['inter'],
'sort len':['len'],
'sort mdiff':['mdiff'],
'sort minmax':['minmax'],
'sort rev':['sortd'],
'sort sort':['sort'],
'sort sortd':['sortd'],
'sortd diff':['diff'],
'sortd drop':['drop'],
'sortd inter':['inter'],
'sortd len':['len'],
'sortd mdiff':['mdiff'],
'sortd minmax':['minmax'],
'sortd rev':['sort'],
'sq 0 max2':['sq'],
'sq abs':['sq'],
'sq drop':['drop'],
'sq len':['len'],
'sq lens':['lens'],
'sq pal':['pal'],
'sqrt abs':['sqrt'],
'sqrt drop':['drop'],
'sqrt len':['len'],
'sqrt lens':['lens'],
'sqrt pal':['pal'],
'str drop':['drop'],
'sublists drop':['drop'],
'suffixes drop':['drop'],
'suffixes len':['len'],
'suffixes uniq':['suffixes'],
'suffixes zip':['suffixes'],
'sum drop':['drop'],
'sum len':['len'],
'swap *':['*'],
'swap +':['+'],
'swap <':['>'],
'swap =':['='],
'swap >':['<'],
'swap band':['band'],
'swap bor':['bor'],
'swap bxor':['bxor'],
'swap eql':['eql'],
'swap gcd':['gcd'],
'swap max2':['max2'],
'swap min2':['min2'],
'tail drop':['drop'],
'undig drop':['drop'],
'undig len':['len'],
'undig pal':['pal'],
'uniq diff':['diff'],
'uniq drop':['drop'],
'uniq head':['head'],
'uniq inter':['inter'],
'uniq uniq':['uniq'],
'up drop':['drop'],
'up up':['up'],
'where abs':['where'],
'where any':['any'],
'where ceil':['where'],
'where drop':['drop'],
'where floor':['where'],
'where round':['where'],
'where sort':['where'],
'where uniq':['where'],
'words drop':['drop'],
'wrap drop':['drop'],
'wrap rev':['wrap'],
'wrap sort':['wrap'],
'wrap sortd':['wrap'],
'wrap sum head':['sum'],
'wrap sum last':['sum'],
'wrap sum sum':['sum'],
'wrap uniq':['wrap'],
'zip drop':['drop'],
'- drop':['drop','drop'],
'- len':['+','len'],
'* drop':['drop','drop'],
'* len':['+','len'],
'/ drop':['drop','drop'],
'/ len':['+','len'],
'% drop':['drop','drop'],
'% len':['+','len'],
'+ drop':['drop','drop'],
'< base':['=','base'],
'< divs':['<','range'],
'< drop':['drop','drop'],
'< fact':['=','fact'],
'< frac':['=','frac'],
'< isint':['=','isint'],
'< issq':['=','issq'],
'< len':['+','len'],
'< prime':['=','prime'],
'= divs':['=','range'],
'= drop':['drop','drop'],
'= len':['+','len'],
'> base':['=','base'],
'> divs':['>','range'],
'> drop':['drop','drop'],
'> fact':['=','fact'],
'> frac':['=','frac'],
'> isint':['=','isint'],
'> issq':['=','issq'],
'> len':['+','len'],
'> prime':['=','prime'],
'0 *':['dup','-'],
'0 /':['dup','<'],
'0 %':['dup','<'],
'0 < abs':['0','<'],
'0 < not':['dup','ncr'],
'0 < sq':['0','<'],
'0 = abs':['0','='],
'0 = sq':['0','='],
'0 = sum':['0','count'],
'0 > abs':['0','>'],
'0 > not':['sqrt','not'],
'0 > sq':['0','>'],
'0 0':['0','dup'],
'0 1 pair':['2','iota0'],
'0 1 swap':['1','0'],
'0 10 -':['10','neg'],
'0 10 swap':['10','0'],
'0 2 -':['2','neg'],
'0 2 swap':['2','0'],
'0 band':['dup','<'],
'0 bor':['dup','band'],
'0 bxor':['dup','band'],
'0 dec /':['neg','floor'],
'0 dec dec':['2','neg'],
'0 div':['dup','<'],
'0 divs':['0','range'],
'0 dup abs':['0','dup'],
'0 dup inc':['0','1'],
'0 dup neg':['0','dup'],
'0 dup not':['0','1'],
'0 dup sq':['0','dup'],
'0 dvd':['dup','<'],
'0 iota0':['0','range'],
'0 max2 abs':['0','max2'],
'0 max2 not':['sqrt','not'],
'0 min2 not':['dup','ncr'],
'0 ncr':['dup','ncr'],
'0 npr':['dup','ncr'],
'0 over -':['dup','neg'],
'0 over swap':['dup','0'],
'0 pair len':['drop','2'],
'0 pfac':['0','range'],
'0 primes':['0','range'],
'0 rep':['dup','diff'],
'0 rot -':['swap','neg'],
'0 rot swap':['swap','0'],
'0 swap /':['dup','<'],
'0 swap %':['dup','<'],
'0 swap drop':['drop','0'],
'0 take':['dup','diff'],
'0 wrap':['0','digits'],
'1 < abs':['1','<'],
'1 < sq':['1','<'],
'1 = abs':['1','='],
'1 = sq':['1','='],
'1 = sum':['1','count'],
'1 > abs':['1','>'],
'1 > sq':['1','>'],
'1 0 pair':['10','digits'],
'1 0 swap':['0','1'],
'1 1':['1','dup'],
'1 10 +':['10','inc'],
'1 10 swap':['10','1'],
'1 2 -':['0','dec'],
'1 2 +':['2','inc'],
'1 2 pair':['2','range'],
'1 2 swap':['2','1'],
'1 base':['0','base'],
'1 chunks':['1','combs'],
'1 digits':['1','range'],
'1 divs':['1','range'],
'1 dup abs':['1','dup'],
'1 dup dec':['1','0'],
'1 dup inc':['1','2'],
'1 dup not':['1','0'],
'1 dup sq':['1','dup'],
'1 iota0':['0','digits'],
'1 max2 abs':['1','max2'],
'1 neg':['0','dec'],
'1 npr':['1','ncr'],
'1 over +':['dup','inc'],
'1 over swap':['dup','1'],
'1 pair len':['drop','2'],
'1 pfac':['0','range'],
'1 primes':['0','range'],
'1 rot +':['swap','inc'],
'1 rot swap':['swap','1'],
'1 swap -':['dec','neg'],
'1 swap drop':['drop','1'],
'1 windows':['1','combs'],
'1 wrap':['1','range'],
'10 % abs':['10','%'],
'10 < abs':['10','<'],
'10 < sq':['10','<'],
'10 = abs':['10','='],
'10 = sq':['10','='],
'10 > abs':['10','>'],
'10 > sq':['10','>'],
'10 0 swap':['0','10'],
'10 1 swap':['1','10'],
'10 10':['10','dup'],
'10 2 swap':['2','10'],
'10 dec abs':['10','dec'],
'10 dup abs':['10','dup'],
'10 dup not':['10','0'],
'10 inc abs':['10','inc'],
'10 isqrt':['2','inc'],
'10 max2 abs':['10','max2'],
'10 neg -':['10','+'],
'10 neg +':['10','-'],
'10 over swap':['dup','10'],
'10 pair len':['drop','2'],
'10 pair sum':['10','+'],
'10 rot swap':['swap','10'],
'10 swap drop':['drop','10'],
'2 *':['dup','+'],
'2 % abs':['2','%'],
'2 < abs':['2','<'],
'2 < sq':['2','<'],
'2 = abs':['2','='],
'2 = sq':['2','='],
'2 = sum':['2','count'],
'2 > abs':['2','>'],
'2 > sq':['2','>'],
'2 0 swap':['0','2'],
'2 1 swap':['1','2'],
'2 10 swap':['10','2'],
'2 2':['2','dup'],
'2 divs':['2','range'],
'2 dup +':['2','sq'],
'2 dup abs':['2','dup'],
'2 dup dec':['2','1'],
'2 dup not':['2','0'],
'2 inc abs':['2','inc'],
'2 inc inc':['2','sq'],
'2 inc sq':['10','dec'],
'2 max2 abs':['2','max2'],
'2 neg -':['2','+'],
'2 neg +':['2','-'],
'2 nthp':['2','inc'],
'2 over swap':['dup','2'],
'2 pair len':['drop','2'],
'2 pair sum':['2','+'],
'2 pfac':['2','digits'],
'2 primes':['2','digits'],
'2 rep':['dup','cat'],
'2 rot swap':['swap','2'],
'2 sq dec':['2','inc'],
'2 swap drop':['drop','2'],
'2 wrap':['2','digits'],
'abs * abs':['*','abs'],
'abs * not':['*','not'],
'abs * sq':['*','sq'],
'abs % not':['%','not'],
'abs + len':['+','len'],
'abs 0 <':['dup','<'],
'abs 0 =':['0','='],
'abs 0 >':['not','not'],
'abs cat abs':['cat','abs'],
'abs cat len':['cat','len'],
'abs cat not':['cat','not'],
'abs cat sq':['cat','sq'],
'abs dup -':['dup','-'],
'abs dup /':['dup','/'],
'abs dup %':['dup','%'],
'abs dup <':['dup','<'],
'abs dup =':['dup','='],
'abs dup abs':['abs','dup'],
'abs dup eql':['dup','eql'],
'abs head':['head','abs'],
'abs inc abs':['abs','inc'],
'abs last':['last','abs'],
'abs pair abs':['pair','abs'],
'abs pair len':['pair','len'],
'abs pair not':['pair','not'],
'abs pair sq':['pair','sq'],
'abs rev':['rev','abs'],
'abs sign':['not','not'],
'all divs':['all','range'],
'all even':['not','max'],
'all fact':['all','issq'],
'all frac':['all','prime'],
'all isint':['all','issq'],
'all not':['not','max'],
'all pfac':['all','primes'],
'all rev':['rev','all'],
'alpha alpha':['alpha','dup'],
'ALPHA ALPHA':['ALPHA','dup'],
'alpha bins':['alpha','group'],
'ALPHA bins':['ALPHA','group'],
'alpha chars':['alpha','group'],
'ALPHA chars':['ALPHA','group'],
'alpha count':['drop','0'],
'ALPHA count':['drop','0'],
'alpha eql':['drop','0'],
'ALPHA eql':['drop','0'],
'alpha has':['drop','0'],
'ALPHA has':['drop','0'],
'alpha idxof':['drop','0'],
'ALPHA idxof':['drop','0'],
'ALPHA len':['alpha','len'],
'alpha sortd':['alpha','rev'],
'ALPHA sortd':['ALPHA','rev'],
'alpha words':['alpha','wrap'],
'ALPHA words':['ALPHA','wrap'],
'alt abs':['abs','alt'],
'alt ceil':['ceil','alt'],
'alt dec':['dec','alt'],
'alt dsum':['dsum','alt'],
'alt even':['even','alt'],
'alt fact':['fact','alt'],
'alt fib':['fib','alt'],
'alt floor':['floor','alt'],
'alt frac':['frac','alt'],
'alt inc':['inc','alt'],
'alt isint':['isint','alt'],
'alt isqrt':['isqrt','alt'],
'alt issq':['issq','alt'],
'alt len':['drop','2'],
'alt lens':['halves','lens'],
'alt neg':['neg','alt'],
'alt not':['not','alt'],
'alt nthp':['nthp','alt'],
'alt prime':['prime','alt'],
'alt round':['round','alt'],
'alt sign':['sign','alt'],
'alt sq':['sq','alt'],
'alt sqrt':['sqrt','alt'],
'any all':['any','prod'],
'any base':['all','base'],
'any divs':['any','range'],
'any even':['not','prod'],
'any fact':['all','issq'],
'any frac':['all','prime'],
'any isint':['all','issq'],
'any issq':['all','issq'],
'any last':['last','any'],
'any not':['not','prod'],
'any pfac':['all','primes'],
'any prime':['all','prime'],
'any primes':['all','primes'],
'any rev':['rev','any'],
'band drop':['drop','drop'],
'band frac':['=','frac'],
'band isint':['=','isint'],
'band len':['+','len'],
'base drop':['drop','drop'],
'bins any':['bins','all'],
'bins len':['uniq','len'],
'bins pal':['uniq','pal'],
'bor drop':['drop','drop'],
'bor frac':['=','frac'],
'bor isint':['=','isint'],
'bor len':['+','len'],
'bxor drop':['drop','drop'],
'bxor frac':['=','frac'],
'bxor isint':['=','isint'],
'bxor len':['+','len'],
'cart drop':['drop','drop'],
'cat drop':['drop','drop'],
'cat dup eql':['eql','issq'],
'ceil digits':['neg','digits'],
'ceil dsum':['neg','dsum'],
'ceil frac':['floor','frac'],
'ceil head':['head','ceil'],
'ceil init':['init','ceil'],
'ceil isint':['floor','isint'],
'ceil last':['last','ceil'],
'ceil max':['max','ceil'],
'ceil min':['min','ceil'],
'ceil minmax':['minmax','ceil'],
'ceil neg':['neg','floor'],
'ceil prefixes':['prefixes','ceil'],
'ceil rev':['rev','ceil'],
'ceil sort':['sort','ceil'],
'ceil sortd':['sortd','ceil'],
'ceil suffixes':['suffixes','ceil'],
'ceil tail':['tail','ceil'],
'chars init':['init','chars'],
'chars lens':['ord','isint'],
'chars rev':['rev','chars'],
'chars sort':['sort','chars'],
'chars sortd':['sortd','chars'],
'chars tail':['tail','chars'],
'chars uniq':['uniq','group'],
'chr flat':['flat','chr'],
'chr zip':['zip','chr'],
'chunks drop':['drop','drop'],
'combs drop':['drop','drop'],
'count drop':['drop','drop'],
'count frac':['has','prime'],
'count isint':['has','issq'],
'cumsum init':['init','cumsum'],
'cumsum neg':['neg','cumsum'],
'cumsum prefixes':['prefixes','cumsum'],
'dec + len':['+','len'],
'dec 0 <':['1','<'],
'dec 0 =':['1','='],
'dec 0 >':['1','>'],
'dec 1 <':['2','<'],
'dec 1 =':['2','='],
'dec 1 >':['2','>'],
'dec cat len':['cat','len'],
'dec dup -':['dup','-'],
'dec dup %':['dup','%'],
'dec dup <':['dup','<'],
'dec dup =':['dup','='],
'dec dup eql':['dup','eql'],
'dec grade':['inc','grade'],
'dec head len':['head','len'],
'dec last len':['last','len'],
'dec pair len':['pair','len'],
'dec pal':['inc','pal'],
'dec sq not':['dec','not'],
'deltas init':['init','deltas'],
'deltas neg':['neg','deltas'],
'deltas tail':['tail','deltas'],
'diff drop':['drop','drop'],
'digs bins':['digs','group'],
'digs chars':['digs','group'],
'digs digs':['digs','dup'],
'digs eql':['drop','0'],
'digs head':['0','str'],
'digs sortd':['digs','rev'],
'digs words':['digs','wrap'],
'div base':['/','base'],
'div drop':['drop','drop'],
'div fact':['/','fact'],
'div len':['+','len'],
'div pad':['/','pad'],
'div primes':['/','primes'],
'divs all':['drop','1'],
'divs any':['divs','min'],
'divs bins':['divs','group'],
'divs frac':['divs','not'],
'divs grade':['divs','where'],
'divs head':['divs','min'],
'divs last':['divs','max'],
'divs sign':['divs','isint'],
'divs sortd':['divs','rev'],
'dsum frac':['not','prime'],
'dsum head':['head','dsum'],
'dsum isint':['not','issq'],
'dsum last':['last','dsum'],
'dsum rev':['rev','dsum'],
'dup - abs':['dup','-'],
'dup - neg':['dup','-'],
'dup - not':['0','pow'],
'dup - sq':['dup','-'],
'dup / abs':['dup','/'],
'dup / sq':['dup','/'],
'dup % abs':['dup','%'],
'dup % neg':['dup','%'],
'dup % not':['0','pow'],
'dup % sq':['dup','%'],
'dup < abs':['dup','<'],
'dup < head':['drop','0'],
'dup < inc':['0','pow'],
'dup < last':['drop','0'],
'dup < neg':['dup','<'],
'dup < not':['0','pow'],
'dup < rev':['dup','<'],
'dup < sq':['dup','<'],
'dup < sum':['drop','0'],
'dup = abs':['dup','='],
'dup = sq':['dup','='],
'dup >':['dup','<'],
'dup 0 rot':['0','over'],
'dup 0 swap':['0','over'],
'dup 1 rot':['1','over'],
'dup 1 swap':['1','over'],
'dup 10 rot':['10','over'],
'dup 10 swap':['10','over'],
'dup 2 rot':['2','over'],
'dup 2 swap':['2','over'],
'dup abs %':['dup','%'],
'dup abs <':['0','<'],
'dup abs >':['dup','<'],
'dup bor':['dup','band'],
'dup bxor':['dup','<'],
'dup dec <':['dup','<'],
'dup div':['dup','/'],
'dup dup rot':['dup','dup'],
'dup eql -':['drop','dec'],
'dup eql /':['drop','floor'],
'dup eql %':['drop','frac'],
'dup eql +':['drop','inc'],
'dup eql dec':['drop','0'],
'dup eql inc':['drop','2'],
'dup eql not':['drop','0'],
'dup has':['dup','eql'],
'dup idxof':['dup','eql'],
'dup inc >':['dup','<'],
'dup mdiff':['dup','diff'],
'dup neg -':['dup','+'],
'dup neg *':['sq','neg'],
'dup neg %':['dup','%'],
'dup neg +':['dup','-'],
'dup neg <':['0','<'],
'dup neg =':['0','='],
'dup neg >':['0','>'],
'dup neg min2':['abs','neg'],
'dup not *':['dup','-'],
'dup not =':['dup','<'],
'dup not >':['0','>'],
'dup not min2':['0','min2'],
'dup over':['dup','dup'],
'dup pair len':['drop','2'],
'dup rot rot':['swap','over'],
'dup rot swap':['swap','over'],
'dup wrap *':['sq','wrap'],
'dvd base':['=','base'],
'dvd divs':['dvd','range'],
'dvd drop':['drop','drop'],
'dvd fact':['=','fact'],
'dvd frac':['=','frac'],
'dvd isint':['=','isint'],
'dvd issq':['=','issq'],
'dvd len':['+','len'],
'dvd prime':['=','prime'],
'eql % abs':['eql','%'],
'eql < abs':['eql','<'],
'eql < sq':['eql','<'],
'eql = abs':['eql','='],
'eql = sq':['eql','='],
'eql = sum':['eql','count'],
'eql > abs':['eql','>'],
'eql > sq':['eql','>'],
'eql 0 <':['eql','prime'],
'eql 0 =':['eql','not'],
'eql 0 min2':['eql','prime'],
'eql 1 <':['eql','not'],
'eql 1 >':['eql','prime'],
'eql 1 max2':['eql','issq'],
'eql 10 /':['eql','prime'],
'eql 10 <':['eql','issq'],
'eql 10 =':['eql','prime'],
'eql 10 >':['eql','prime'],
'eql 2 /':['eql','prime'],
'eql 2 <':['eql','issq'],
'eql 2 =':['eql','prime'],
'eql 2 >':['eql','prime'],
'eql dec abs':['eql','not'],
'eql dec neg':['eql','not'],
'eql dec sq':['eql','not'],
'eql divs':['eql','range'],
'eql drop':['drop','drop'],
'eql dup -':['eql','prime'],
'eql dup %':['eql','prime'],
'eql dup +':['eql','nthp'],
'eql dup <':['eql','prime'],
'eql dup =':['eql','issq'],
'eql dup abs':['eql','dup'],
'eql dup sq':['eql','dup'],
'eql even':['eql','not'],
'eql fact':['eql','issq'],
'eql frac':['eql','prime'],
'eql inc abs':['eql','inc'],
'eql inc not':['eql','prime'],
'eql isint':['eql','issq'],
'eql max2 abs':['eql','max2'],
'eql neg -':['eql','+'],
'eql neg +':['eql','-'],
'eql not dec':['eql','neg'],
'eql not neg':['eql','dec'],
'eql npr':['eql','ncr'],
'eql pair sum':['eql','+'],
'eql pfac':['eql','primes'],
'eql wrap':['eql','digits'],
'even all':['even','prod'],
'even any':['even','max'],
'even base':['not','base'],
'even divs':['even','range'],
'even even':['even','not'],
'even fact':['not','issq'],
'even frac':['not','prime'],
'even isint':['not','issq'],
'even issq':['not','issq'],
'even npr':['even','ncr'],
'even pfac':['not','primes'],
'even prime':['not','prime'],
'even primes':['not','primes'],
'even rev':['rev','even'],
'fact frac':['not','prime'],
'fact init':['init','fact'],
'fact isint':['not','issq'],
'fact prefixes':['prefixes','fact'],
'fact rev':['rev','fact'],
'fact sign':['sign','issq'],
'fact sort':['sort','fact'],
'fact sortd':['sortd','fact'],
'fact suffixes':['suffixes','fact'],
'fact tail':['tail','fact'],
'fib frac':['not','prime'],
'fib head':['head','fib'],
'fib init':['init','fib'],
'fib isint':['not','issq'],
'fib keep':['sqrt','keep'],
'fib last':['last','fib'],
'fib min':['min','fib'],
'fib not':['sqrt','not'],
'fib prefixes':['prefixes','fib'],
'fib rev':['rev','fib'],
'fib sign':['sqrt','sign'],
'fib suffixes':['suffixes','fib'],
'fib tail':['tail','fib'],
'fib where':['sqrt','where'],
'flat ceil':['ceil','flat'],
'flat dec':['dec','flat'],
'flat dsum':['dsum','flat'],
'flat even':['even','flat'],
'flat fact':['fact','flat'],
'flat fib':['fib','flat'],
'flat floor':['floor','flat'],
'flat frac':['frac','flat'],
'flat inc':['inc','flat'],
'flat isint':['isint','flat'],
'flat isqrt':['isqrt','flat'],
'flat issq':['issq','flat'],
'flat len':['lens','sum'],
'flat max':['max','max'],
'flat min':['min','min'],
'flat neg':['neg','flat'],
'flat not':['not','flat'],
'flat nthp':['nthp','flat'],
'flat prime':['prime','flat'],
'flat sign':['sign','flat'],
'flat sq':['sq','flat'],
'flat sqrt':['sqrt','flat'],
'floor head':['head','floor'],
'floor last':['last','floor'],
'floor max':['max','floor'],
'floor min':['min','floor'],
'floor neg':['neg','ceil'],
'floor rev':['rev','floor'],
'floor sort':['sort','floor'],
'frac fact':['not','issq'],
'frac head':['head','frac'],
'frac init':['init','frac'],
'frac isqrt':['frac','floor'],
'frac last':['last','frac'],
'frac pfac':['not','primes'],
'frac prefixes':['prefixes','frac'],
'frac prime':['not','prime'],
'frac primes':['not','primes'],
'frac rev':['rev','frac'],
'frac suffixes':['suffixes','frac'],
'frac tail':['tail','frac'],
'gcd drop':['drop','drop'],
'gcd len':['+','len'],
'grade all':['drop','1'],
'grade isint':['not','issq'],
'grade keep':['len','take'],
'grade pal':['prefixes','pal'],
'grade prod':['len','fact'],
'grade sign':['not','issq'],
'grade sort':['len','range'],
'grade sortd':['suffixes','lens'],
'grade where':['len','range'],
'group abs':['abs','group'],
'group any':['group','all'],
'group neg':['neg','group'],
'group sq':['sq','group'],
'group sqrt':['sqrt','group'],
'halves abs':['abs','halves'],
'halves ceil':['ceil','halves'],
'halves dec':['dec','halves'],
'halves dsum':['dsum','halves'],
'halves even':['even','halves'],
'halves fact':['fact','halves'],
'halves fib':['fib','halves'],
'halves floor':['floor','halves'],
'halves frac':['frac','halves'],
'halves inc':['inc','halves'],
'halves isint':['isint','halves'],
'halves isqrt':['isqrt','halves'],
'halves issq':['issq','halves'],
'halves len':['drop','2'],
'halves neg':['neg','halves'],
'halves not':['not','halves'],
'halves nthp':['nthp','halves'],
'halves prime':['prime','halves'],
'halves round':['round','halves'],
'halves sign':['sign','halves'],
'halves sq':['sq','halves'],
'halves sqrt':['sqrt','halves'],
'has divs':['has','range'],
'has drop':['drop','drop'],
'has even':['has','not'],
'has fact':['has','issq'],
'has frac':['has','prime'],
'has isint':['has','issq'],
'has npr':['has','ncr'],
'has pfac':['has','primes'],
'has wrap':['has','digits'],
'head dup eql':['dup','eql'],
'head head head':['head','head'],
'head head last':['head','head'],
'head head rev':['head','head'],
'head last head':['head','last'],
'head last last':['head','last'],
'head last rev':['head','last'],
'head max':['max','head'],
'head min':['min','head'],
'head sum':['sum','head'],
'idx drop':['drop','drop'],
'idxof drop':['drop','drop'],
'idxof frac':['has','prime'],
'idxof isint':['has','issq'],
'idxof not':['has','not'],
'inc + len':['+','len'],
'inc 2 <':['1','<'],
'inc cat len':['cat','len'],
'inc dup -':['dup','-'],
'inc dup %':['dup','%'],
'inc dup <':['dup','<'],
'inc dup =':['dup','='],
'inc dup eql':['dup','eql'],
'inc head len':['head','len'],
'inc last len':['last','len'],
'inc pair len':['pair','len'],
'inc sq not':['inc','not'],
'init abs':['abs','init'],
'init dec':['dec','init'],
'init even':['even','init'],
'init floor':['floor','init'],
'init inc':['inc','init'],
'init isint':['isint','init'],
'init issq':['issq','init'],
'init len':['tail','len'],
'init neg':['neg','init'],
'init not':['not','init'],
'init prime':['prime','init'],
'init rev':['rev','tail'],
'init sq':['sq','init'],
'init sqrt':['sqrt','init'],
'init tail':['tail','init'],
'inter drop':['drop','drop'],
'iota0 all':['iota0','prod'],
'iota0 bins':['iota0','group'],
'iota0 deltas':['range','deltas'],
'iota0 frac':['range','not'],
'iota0 head':['drop','0'],
'iota0 init':['dec','iota0'],
'iota0 isint':['range','isint'],
'iota0 last':['iota0','max'],
'iota0 len':['range','max'],
'iota0 min':['drop','0'],
'iota0 pal':['range','pal'],
'iota0 sortd':['iota0','rev'],
'iota0 tail':['dec','range'],
'iota0 where':['range','tail'],
'isint all':['isint','prod'],
'isint any':['isint','max'],
'isint base':['not','base'],
'isint divs':['isint','range'],
'isint even':['isint','not'],
'isint fact':['not','issq'],
'isint frac':['not','prime'],
'isint isint':['not','issq'],
'isint issq':['not','issq'],
'isint npr':['isint','ncr'],
'isint pfac':['not','primes'],
'isint prime':['not','prime'],
'isint primes':['not','primes'],
'isint rev':['rev','isint'],
'isqrt head':['head','isqrt'],
'isqrt idx':['sqrt','idx'],
'isqrt init':['init','isqrt'],
'isqrt iota0':['sqrt','iota0'],
'isqrt last':['last','isqrt'],
'isqrt max':['max','isqrt'],
'isqrt min':['min','isqrt'],
'isqrt minmax':['minmax','isqrt'],
'isqrt pad':['sqrt','pad'],
'isqrt prefixes':['prefixes','isqrt'],
'isqrt primes':['sqrt','primes'],
'isqrt range':['sqrt','range'],
'isqrt rep':['sqrt','rep'],
'isqrt rev':['rev','isqrt'],
'isqrt rotate':['sqrt','rotate'],
'isqrt skip':['sqrt','skip'],
'isqrt suffixes':['suffixes','isqrt'],
'isqrt tail':['tail','isqrt'],
'isqrt take':['sqrt','take'],
'issq all':['issq','prod'],
'issq any':['issq','max'],
'issq base':['not','base'],
'issq divs':['issq','range'],
'issq even':['issq','not'],
'issq fact':['not','issq'],
'issq frac':['not','prime'],
'issq isint':['not','issq'],
'issq issq':['not','issq'],
'issq npr':['issq','ncr'],
'issq pfac':['not','primes'],
'issq prime':['not','prime'],
'issq primes':['not','primes'],
'issq rev':['rev','issq'],
'join drop':['drop','drop'],
'keep drop':['drop','drop'],
'last dup eql':['dup','eql'],
'last head head':['last','head'],
'last head last':['last','head'],
'last head rev':['last','head'],
'last last head':['last','last'],
'last last last':['last','last'],
'last last rev':['last','last'],
'last max':['max','last'],
'last min':['min','last'],
'last sum':['sum','last'],
'len % abs':['len','%'],
'len + len':['drop','len'],
'len < abs':['len','<'],
'len < sq':['len','<'],
'len = abs':['len','='],
'len = sq':['len','='],
'len = sum':['len','count'],
'len > abs':['len','>'],
'len > sq':['len','>'],
'len 0 <':['drop','0'],
'len 0 =':['len','not'],
'len 0 >':['len','sign'],
'len 0 min2':['drop','0'],
'len 1 <':['len','not'],
'len 1 min2':['len','sign'],
'len dup -':['drop','0'],
'len dup /':['len','sign'],
'len dup %':['drop','0'],
'len dup <':['drop','0'],
'len dup =':['dup','eql'],
'len dup abs':['len','dup'],
'len frac':['drop','0'],
'len inc abs':['len','inc'],
'len inc not':['drop','0'],
'len isint':['drop','1'],
'len max2 abs':['len','max2'],
'len neg -':['len','+'],
'len neg +':['len','-'],
'len not not':['len','sign'],
'len pair sum':['len','+'],
'len sq not':['len','not'],
'lens head':['head','len'],
'lens init':['init','lens'],
'lens last':['last','len'],
'lens rev':['rev','lens'],
'lens tail':['tail','lens'],
'low flat':['flat','low'],
'low wrap':['wrap','low'],
'max2 drop':['drop','drop'],
'max2 len':['+','len'],
'mdiff drop':['drop','drop'],
'min grade':['max','grade'],
'min pal':['max','pal'],
'min2 drop':['drop','drop'],
'min2 len':['+','len'],
'minmax alt':['minmax','halves'],
'minmax bins':['minmax','group'],
'minmax floor':['floor','minmax'],
'minmax init':['min','wrap'],
'minmax len':['drop','2'],
'minmax sortd':['minmax','rev'],
'minmax tail':['max','wrap'],
'ncr drop':['drop','drop'],
'ncr frac':['=','frac'],
'ncr isint':['=','isint'],
'ncr len':['+','len'],
'neg - abs':['+','abs'],
'neg - not':['+','not'],
'neg - sq':['+','sq'],
'neg * abs':['*','abs'],
'neg * not':['*','not'],
'neg * sq':['*','sq'],
'neg % not':['%','not'],
'neg + abs':['-','abs'],
'neg + len':['+','len'],
'neg + not':['-','not'],
'neg + sq':['-','sq'],
'neg 0 <':['0','>'],
'neg 0 =':['0','='],
'neg 0 >':['0','<'],
'neg cat abs':['cat','abs'],
'neg cat len':['cat','len'],
'neg cat not':['cat','not'],
'neg cat sq':['cat','sq'],
'neg dec':['inc','neg'],
'neg dup -':['dup','-'],
'neg dup /':['dup','/'],
'neg dup %':['dup','%'],
'neg dup <':['dup','<'],
'neg dup =':['dup','='],
'neg dup eql':['dup','eql'],
'neg head':['head','neg'],
'neg inc':['dec','neg'],
'neg last':['last','neg'],
'neg max':['min','neg'],
'neg min':['max','neg'],
'neg pair abs':['pair','abs'],
'neg pair len':['pair','len'],
'neg pair not':['pair','not'],
'neg pair sq':['pair','sq'],
'neg rev':['rev','neg'],
'neg sum':['sum','neg'],
'not + len':['+','len'],
'not 0 <':['dup','<'],
'not 0 =':['not','not'],
'not 0 min2':['dup','<'],
'not 1 <':['not','not'],
'not 1 >':['dup','<'],
'not 1 max2':['0','pow'],
'not 10 /':['dup','<'],
'not 10 <':['0','pow'],
'not 10 =':['dup','<'],
'not 10 >':['dup','<'],
'not 2 /':['dup','<'],
'not 2 <':['0','pow'],
'not 2 =':['dup','<'],
'not 2 >':['dup','<'],
'not all':['not','prod'],
'not any':['not','max'],
'not cat len':['cat','len'],
'not dec abs':['not','not'],
'not dec neg':['not','not'],
'not dec sq':['not','not'],
'not divs':['not','range'],
'not dup -':['dup','<'],
'not dup %':['dup','<'],
'not dup +':['not','nthp'],
'not dup <':['dup','<'],
'not dup =':['0','pow'],
'not dup abs':['not','dup'],
'not dup eql':['dup','eql'],
'not dup sq':['not','dup'],
'not even':['not','not'],
'not fact':['not','issq'],
'not frac':['not','prime'],
'not head abs':['not','head'],
'not head len':['head','len'],
'not head sq':['not','head'],
'not inc abs':['not','inc'],
'not inc not':['not','prime'],
'not isint':['not','issq'],
'not last abs':['not','last'],
'not last len':['last','len'],
'not last sq':['not','last'],
'not not dec':['not','neg'],
'not not neg':['not','dec'],
'not npr':['not','ncr'],
'not pair len':['pair','len'],
'not pfac':['not','primes'],
'not rev abs':['not','rev'],
'not rev eql':['not','eql'],
'not rev sq':['not','rev'],
'npr drop':['drop','drop'],
'npr frac':['=','frac'],
'npr isint':['=','isint'],
'npr len':['+','len'],
'nthp frac':['not','prime'],
'nthp head':['head','nthp'],
'nthp init':['init','nthp'],
'nthp isint':['not','issq'],
'nthp issq':['isqrt','not'],
'nthp last':['last','nthp'],
'nthp min':['min','nthp'],
'nthp prime':['isqrt','sign'],
'nthp rev':['rev','nthp'],
'nthp tail':['tail','nthp'],
'num head':['head','num'],
'num init':['init','num'],
'num last':['last','num'],
'num rev':['rev','num'],
'num tail':['tail','num'],
'ord alt':['alt','ord'],
'ord bins':['bins','ord'],
'ord flat':['flat','ord'],
'ord frac':['ord','not'],
'ord group':['group','ord'],
'ord halves':['halves','ord'],
'ord idxof':['ord','has'],
'ord init':['init','ord'],
'ord keep':['len','take'],
'ord perms':['perms','ord'],
'ord powerset':['powerset','ord'],
'ord prefixes':['prefixes','ord'],
'ord rev':['rev','ord'],
'ord sign':['ord','isint'],
'ord sort':['sort','ord'],
'ord sortd':['sortd','ord'],
'ord sublists':['sublists','ord'],
'ord suffixes':['suffixes','ord'],
'ord tail':['tail','ord'],
'ord uniq':['uniq','ord'],
'ord where':['len','range'],
'ord wrap':['wrap','ord'],
'ord zip':['zip','ord'],
'over pair len':['drop','2'],
'over rot':['swap','dup'],
'over swap drop':['drop','dup'],
'pad any':['drop','any'],
'pad drop':['drop','drop'],
'pad num':['drop','num'],
'pad sum':['drop','sum'],
'pad undig':['drop','undig'],
'pad words':['drop','words'],
'pair alt':['pair','halves'],
'pair dec head':['drop','dec'],
'pair drop':['drop','drop'],
'pair dup len':['pair','2'],
'pair inc head':['drop','inc'],
'pair init':['drop','wrap'],
'pair last':['swap','drop'],
'pair not head':['drop','not'],
'pair rev':['swap','pair'],
'pair sum head':['drop','sum'],
'pair wrap sum':['+','wrap'],
'pal divs':['pal','range'],
'pal even':['pal','not'],
'pal fact':['drop','1'],
'pal frac':['drop','0'],
'pal isint':['drop','1'],
'pal issq':['drop','1'],
'pal npr':['pal','ncr'],
'pal pfac':['pal','primes'],
'pal prime':['drop','0'],
'pal wrap':['pal','digits'],
'perms abs':['abs','perms'],
'perms ceil':['ceil','perms'],
'perms dec':['dec','perms'],
'perms dsum':['dsum','perms'],
'perms even':['even','perms'],
'perms fact':['fact','perms'],
'perms fib':['fib','perms'],
'perms floor':['floor','perms'],
'perms frac':['frac','perms'],
'perms inc':['inc','perms'],
'perms isint':['isint','perms'],
'perms isqrt':['isqrt','perms'],
'perms issq':['issq','perms'],
'perms len':['len','fact'],
'perms neg':['neg','perms'],
'perms not':['not','perms'],
'perms nthp':['nthp','perms'],
'perms prime':['prime','perms'],
'perms rev':['rev','perms'],
'perms round':['round','perms'],
'perms sign':['sign','perms'],
'perms sq':['sq','perms'],
'perms sqrt':['sqrt','perms'],
'pfac all':['drop','1'],
'pfac bins':['pfac','group'],
'pfac grade':['pfac','where'],
'pfac head':['pfac','min'],
'pfac issq':['pfac','not'],
'pfac last':['pfac','max'],
'pfac sortd':['pfac','rev'],
'pow drop':['drop','drop'],
'pow len':['+','len'],
'powerset abs':['abs','powerset'],
'powerset ceil':['ceil','powerset'],
'powerset dec':['dec','powerset'],
'powerset dsum':['dsum','powerset'],
'powerset even':['even','powerset'],
'powerset fact':['fact','powerset'],
'powerset fib':['fib','powerset'],
'powerset floor':['floor','powerset'],
'powerset frac':['frac','powerset'],
'powerset inc':['inc','powerset'],
'powerset isint':['isint','powerset'],
'powerset isqrt':['isqrt','powerset'],
'powerset issq':['issq','powerset'],
'powerset neg':['neg','powerset'],
'powerset not':['not','powerset'],
'powerset nthp':['nthp','powerset'],
'powerset pal':['len','not'],
'powerset prime':['prime','powerset'],
'powerset round':['round','powerset'],
'powerset sign':['sign','powerset'],
'powerset sq':['sq','powerset'],
'powerset sqrt':['sqrt','powerset'],
'prefixes abs':['abs','prefixes'],
'prefixes dec':['dec','prefixes'],
'prefixes dsum':['dsum','prefixes'],
'prefixes even':['even','prefixes'],
'prefixes floor':['floor','prefixes'],
'prefixes inc':['inc','prefixes'],
'prefixes init':['init','prefixes'],
'prefixes isint':['isint','prefixes'],
'prefixes issq':['issq','prefixes'],
'prefixes lens':['len','range'],
'prefixes neg':['neg','prefixes'],
'prefixes not':['not','prefixes'],
'prefixes prime':['prime','prefixes'],
'prefixes sortd':['prefixes','rev'],
'prefixes sq':['sq','prefixes'],
'prefixes sqrt':['sqrt','prefixes'],
'prime all':['prime','prod'],
'prime any':['prime','max'],
'prime base':['not','base'],
'prime divs':['prime','range'],
'prime even':['prime','not'],
'prime fact':['not','issq'],
'prime frac':['not','prime'],
'prime head':['head','prime'],
'prime isint':['not','issq'],
'prime issq':['not','issq'],
'prime last':['last','prime'],
'prime npr':['prime','ncr'],
'prime pfac':['not','primes'],
'prime prime':['not','prime'],
'prime primes':['not','primes'],
'prime rev':['rev','prime'],
'primes all':['drop','1'],
'primes any':['iota0','any'],
'primes bins':['primes','group'],
'primes frac':['primes','not'],
'primes grade':['primes','where'],
'primes head':['primes','min'],
'primes issq':['primes','not'],
'primes last':['primes','max'],
'primes prime':['primes','isint'],
'primes sign':['primes','isint'],
'primes sortd':['primes','rev'],
'prod abs':['abs','prod'],
'prod grade':['max','grade'],
'prod pal':['max','pal'],
'prod rev':['rev','prod'],
'range all':['not','issq'],
'range any':['range','min'],
'range bins':['range','group'],
'range frac':['range','not'],
'range lens':['range','max'],
'range prefixes':['range','range'],
'range sign':['range','isint'],
'rep drop':['drop','drop'],
'rep head':['take','head'],
'rev + len':['+','len'],
'rev cat len':['cat','len'],
'rev dec':['dec','rev'],
'rev digits':['digits','rev'],
'rev dup <':['dup','<'],
'rev dup eql':['dup','eql'],
'rev inc':['inc','rev'],
'rev not':['not','rev'],
'rev pair len':['pair','len'],
'rev range':['range','rev'],
'rev sum head':['sum','last'],
'rev sum last':['sum','head'],
'rev sum sum':['sum','sum'],
'rng drop':['drop','drop'],
'rot rot swap':['swap','rot'],
'rot swap drop':['drop','swap'],
'rotate diff':['drop','diff'],
'rotate drop':['drop','drop'],
'rotate inter':['drop','inter'],
'rotate len':['drop','len'],
'rotate mdiff':['drop','mdiff'],
'rotate minmax':['drop','minmax'],
'round dec':['dec','round'],
'round frac':['floor','frac'],
'round head':['head','round'],
'round init':['init','round'],
'round isint':['floor','isint'],
'round max':['max','round'],
'round min':['min','round'],
'round minmax':['minmax','round'],
'round prefixes':['prefixes','round'],
'round rev':['rev','round'],
'round sort':['sort','round'],
'round sortd':['sortd','round'],
'round suffixes':['suffixes','round'],
'sign abs':['not','not'],
'sign base':['not','base'],
'sign divs':['sign','range'],
'sign dsum':['not','not'],
'sign fact':['sign','issq'],
'sign fib':['sqrt','sign'],
'sign frac':['not','prime'],
'sign head':['head','sign'],
'sign init':['init','sign'],
'sign isint':['not','issq'],
'sign isqrt':['sqrt','sign'],
'sign last':['last','sign'],
'sign min':['min','sign'],
'sign neg':['neg','sign'],
'sign pfac':['not','primes'],
'sign prefixes':['prefixes','sign'],
'sign prime':['not','prime'],
'sign primes':['not','primes'],
'sign rev':['rev','sign'],
'sign sq':['not','not'],
'sign suffixes':['suffixes','sign'],
'sign tail':['tail','sign'],
'skip drop':['drop','drop'],
'sort dec':['dec','sort'],
'sort grade':['len','range'],
'sort inc':['inc','sort'],
'sortd dec':['dec','sortd'],
'sortd floor':['floor','sortd'],
'sortd head':['sort','last'],
'sortd inc':['inc','sortd'],
'sortd last':['sort','head'],
'sortd pal':['sort','pal'],
'sortd sort':['rev','sort'],
'sortd sortd':['rev','sortd'],
'split drop':['drop','drop'],
'sq + len':['+','len'],
'sq 0 <':['dup','<'],
'sq 10 =':['dup','<'],
'sq 2 =':['dup','<'],
'sq cat len':['cat','len'],
'sq dup -':['dup','-'],
'sq dup %':['dup','%'],
'sq dup <':['dup','<'],
'sq dup =':['dup','='],
'sq dup abs':['sq','dup'],
'sq dup eql':['dup','eql'],
'sq grade':['abs','grade'],
'sq head':['head','sq'],
'sq inc abs':['sq','inc'],
'sq isqrt':['abs','floor'],
'sq last':['last','sq'],
'sq not eql':['not','eql'],
'sq not not':['sq','sign'],
'sq pair len':['pair','len'],
'sq prime':['not','prime'],
'sq rev':['rev','sq'],
'sqrt head':['head','sqrt'],
'sqrt last':['last','sqrt'],
'sqrt min':['min','sqrt'],
'sqrt rev':['rev','sqrt'],
'str words':['wrap','str'],
'str wrap':['wrap','str'],
'sublists abs':['abs','sublists'],
'sublists ceil':['ceil','sublists'],
'sublists dec':['dec','sublists'],
'sublists dsum':['dsum','sublists'],
'sublists even':['even','sublists'],
'sublists fact':['fact','sublists'],
'sublists fib':['fib','sublists'],
'sublists floor':['floor','sublists'],
'sublists frac':['frac','sublists'],
'sublists head':['prefixes','head'],
'sublists inc':['inc','sublists'],
'sublists isint':['isint','sublists'],
'sublists isqrt':['isqrt','sublists'],
'sublists issq':['issq','sublists'],
'sublists last':['suffixes','last'],
'sublists neg':['neg','sublists'],
'sublists not':['not','sublists'],
'sublists nthp':['nthp','sublists'],
'sublists prime':['prime','sublists'],
'sublists round':['round','sublists'],
'sublists sign':['sign','sublists'],
'sublists sq':['sq','sublists'],
'sublists sqrt':['sqrt','sublists'],
'suffixes abs':['abs','suffixes'],
'suffixes dec':['dec','suffixes'],
'suffixes dsum':['dsum','suffixes'],
'suffixes even':['even','suffixes'],
'suffixes floor':['floor','suffixes'],
'suffixes inc':['inc','suffixes'],
'suffixes isint':['isint','suffixes'],
'suffixes issq':['issq','suffixes'],
'suffixes neg':['neg','suffixes'],
'suffixes not':['not','suffixes'],
'suffixes pal':['prefixes','pal'],
'suffixes prime':['prime','suffixes'],
'suffixes sq':['sq','suffixes'],
'suffixes sqrt':['sqrt','suffixes'],
'suffixes tail':['tail','suffixes'],
'sum dup <':['all','prime'],
'sum dup eql':['dup','eql'],
'sum rev sum':['sum','sum'],
'swap - abs':['-','abs'],
'swap - not':['-','not'],
'swap - sq':['-','sq'],
'swap 0 rot':['0','swap'],
'swap 0 swap':['0','rot'],
'swap 1 rot':['1','swap'],
'swap 1 swap':['1','rot'],
'swap 10 rot':['10','swap'],
'swap 10 swap':['10','rot'],
'swap 2 rot':['2','swap'],
'swap 2 swap':['2','rot'],
'swap cat len':['cat','len'],
'swap drop drop':['drop','drop'],
'swap dup rot':['over','swap'],
'swap over swap':['dup','rot'],
'swap pair len':['pair','len'],
'swap rev eql':['rev','eql'],
'swap rot rot':['rot','swap'],
'swap rot swap':['rot','rot'],
'tail abs':['abs','tail'],
'tail dec':['dec','tail'],
'tail even':['even','tail'],
'tail floor':['floor','tail'],
'tail inc':['inc','tail'],
'tail isint':['isint','tail'],
'tail issq':['issq','tail'],
'tail neg':['neg','tail'],
'tail not':['not','tail'],
'tail prime':['prime','tail'],
'tail rev':['rev','init'],
'tail sq':['sq','tail'],
'tail sqrt':['sqrt','tail'],
'take drop':['drop','drop'],
'ubase drop':['drop','drop'],
'undig all':['sum','all'],
'undig any':['sum','any'],
'undig head':['head','undig'],
'undig init':['init','undig'],
'undig keep':['sum','keep'],
'undig last':['last','undig'],
'undig neg':['neg','undig'],
'undig not':['sum','not'],
'undig rev':['rev','undig'],
'undig tail':['tail','undig'],
'undig uniq':['uniq','undig'],
'undig where':['sum','where'],
'uniq abs':['abs','uniq'],
'uniq chars':['uniq','group'],
'uniq neg':['neg','uniq'],
'uniq sq':['sq','uniq'],
'uniq sqrt':['sqrt','uniq'],
'up flat':['flat','up'],
'up rev':['rev','up'],
'up wrap':['wrap','up'],
'where all':['drop','1'],
'where frac':['where','not'],
'where grade':['where','where'],
'where last':['where','max'],
'where sign':['where','isint'],
'where sortd':['where','rev'],
'windows drop':['drop','drop'],
'words low':['low','words'],
'words up':['up','words'],
'wrap abs':['abs','wrap'],
'wrap alt':['wrap','halves'],
'wrap bins':['wrap','prefixes'],
'wrap cat last':['swap','drop'],
'wrap ceil':['ceil','wrap'],
'wrap dec':['dec','wrap'],
'wrap digits':['digits','wrap'],
'wrap dsum':['dsum','wrap'],
'wrap dup cat':['dup','pair'],
'wrap dup eql':['drop','1'],
'wrap dup len':['wrap','1'],
'wrap dup rev':['wrap','dup'],
'wrap even':['even','wrap'],
'wrap fact':['fact','wrap'],
'wrap fib':['fib','wrap'],
'wrap floor':['floor','wrap'],
'wrap frac':['frac','wrap'],
'wrap group':['wrap','prefixes'],
'wrap inc':['inc','wrap'],
'wrap init':['wrap','tail'],
'wrap isint':['isint','wrap'],
'wrap isqrt':['isqrt','wrap'],
'wrap issq':['issq','wrap'],
'wrap len':['drop','1'],
'wrap lens':['len','wrap'],
'wrap neg':['neg','wrap'],
'wrap not':['not','wrap'],
'wrap nthp':['nthp','wrap'],
'wrap pal':['drop','1'],
'wrap perms':['wrap','prefixes'],
'wrap prime':['prime','wrap'],
'wrap range':['range','wrap'],
'wrap round':['round','wrap'],
'wrap sign':['sign','wrap'],
'wrap sq':['sq','wrap'],
'wrap sqrt':['sqrt','wrap'],
'wrap sublists':['wrap','prefixes'],
'wrap suffixes':['wrap','prefixes'],
'wrap sum rev':['sum','wrap'],
'wrap wrap':['wrap','prefixes'],
'zip ceil':['ceil','zip'],
'zip dec':['dec','zip'],
'zip dsum':['dsum','zip'],
'zip even':['even','zip'],
'zip fact':['fact','zip'],
'zip fib':['fib','zip'],
'zip floor':['floor','zip'],
'zip frac':['frac','zip'],
'zip inc':['inc','zip'],
'zip isint':['isint','zip'],
'zip isqrt':['isqrt','zip'],
'zip issq':['issq','zip'],
'zip len':['lens','max'],
'zip neg':['neg','zip'],
'zip not':['not','zip'],
'zip nthp':['nthp','zip'],
'zip prime':['prime','zip'],
'zip sign':['sign','zip'],
'zip sq':['sq','zip'],
'zip sqrt':['sqrt','zip']
};
